import { ResourceManager } from "@/utils/resource.manager";
import { ResourceId } from "@/generated/resourceTypes";
import { hullsData, toHullBlueprint } from "@/config/hulls.data";
import { turretsData, toTurretBlueprint } from "@/config/turrets.data";
import { NEWBIE_DURATION_MS, UP_SCORE_DURATION_MS, PRO_BATTLE_DURATION_MS } from "@/shared/models/passes";

// Resource keys (in resourceTypes.ts) for the supply preview icons. The actual images were
// downloaded from the official CDN into resources/bonuses/<X>/preview, so they're served by OUR
// resource server with our own idLows — works for any client.
export const supplyPreviewResources: Record<string, ResourceId> = {
    health: "bonuses/health/preview",
    armor: "bonuses/armor/preview",
    double_damage: "bonuses/damage/preview",
    n2o: "bonuses/nitro/preview",
    mine: "bonuses/mine/preview",
    "1000_scores": "bonuses/scores/preview",
};

// Preview icons for the subscription passes (category "special", type 5). Downloaded from the official
// CDN into resources/passes/<id>/preview and served with OUR idLows (see ResourceManager) — never the
// official ids (1141/1140/1136).
export const passPreviewResources: Record<string, ResourceId> = {
    newbie: "passes/newbie/preview",
    up_score: "passes/up_score/preview",
    pro_battle: "passes/pro_battle/preview",
    double_crystalls: "passes/double_crystalls/preview",
};

// Preço do Passe de Batalha PRO por RANK do comprador (índice 0 = rank 1 … índice 29 = rank 30).
// Progressão aritmética oficial: base 139, passo +340 (139, 479, 819 … 9999).
export const PRO_BATTLE_PRICE_BY_RANK: number[] = Array.from({ length: 30 }, (_, i) => 139 + i * 340);

/** Preço de um passe para um dado rank: usa `priceByRank` (escala por rank) se houver, senão o fixo. */
export function passPriceForRank(pass: { price: number; priceByRank?: number[] }, rank: number): number {
    if (!pass.priceByRank) return pass.price;
    const idx = Math.min(pass.priceByRank.length, Math.max(1, rank)) - 1;
    return pass.priceByRank[idx];
}

// Pinturas condicionadas ao PREMIUM: não são compradas com cristais nem ficam em `user.paints`. Enquanto
// o premium está ATIVO elas aparecem no depósito (com o tempo restante do premium) e podem ser equipadas;
// quando o premium expira, somem do depósito e, se estiverem equipadas, o sistema volta para a "green"
// (ver buildGarageData/equipItem e a reconciliação de expiração).
export const PREMIUM_PAINT_IDS = new Set<string>(["premium"]);

export const itemBlueprints = {
    turrets: turretsData.map(toTurretBlueprint),
    hulls: hullsData.map(toHullBlueprint),
    paints: [
        {
            id: "green",
            name: "Green",
            description: "",
            isInventory: false,
            index: 1100,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/green/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/green/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/green/texture"),
        },
        {
            id: "holiday",
            name: "Holiday",
            description: "",
            isInventory: false,
            index: 1200,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/holiday/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/holiday/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/holiday/texture"),
        },
        {
            // Pintura PREMIUM (ver PREMIUM_PAINT_IDS): não é comprável — fica disponível enquanto o
            // usuário tem assinatura premium ATIVA. ALL_RESISTANCE 15 = -15% de dano de QUALQUER arma
            // (somado no ItemUtils.getPaintResistancePercent). Dados oficiais (index 702, resources 3370/3371).
            id: "premium",
            name: "Premium",
            description: "",
            isInventory: false,
            index: 702,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/premium/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/premium/preview"),
            rank: 1,
            category: "paint",
            properts: [{ property: "ALL_RESISTANCE", value: "15", subproperties: null }],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/premium/texture"),
        },
        {
            // Pintura ANIMADA (cicla-cor): coloring type 11 / image.tara (tira 1000x1, 1000 frames, 15fps).
            id: "spectrum",
            name: "Spectrum",
            description: "",
            isInventory: false,
            index: 1201,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/spectrum/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/spectrum/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/spectrum/texture"),
        },
        {
            // Pintura ANIMADA: coloring type 11 / image.tara (8x8 de 128px, 64 frames, 24fps).
            id: "first_kiss",
            name: "First Kiss",
            description: "",
            isInventory: false,
            index: 1202,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/first_kiss/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/first_kiss/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/first_kiss/texture"),
        },
        {
            id: "glow",
            name: "Glow",
            description: "",
            isInventory: false,
            index: 1203,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/glow/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/glow/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/glow/texture"),
        },
        {
            id: "monochrome",
            name: "Monochrome",
            description: "",
            isInventory: false,
            index: 1204,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/monochrome/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/monochrome/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/monochrome/texture"),
        },
        {
            id: "turbo",
            name: "Turbo",
            description: "",
            isInventory: false,
            index: 1205,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/turbo/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/turbo/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/turbo/texture"),
        },
        {
            id: "tankoin_tank",
            name: "Tankoin Tank",
            description: "",
            isInventory: false,
            index: 1206,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/tankoin_tank/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/tankoin_tank/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/tankoin_tank/texture"),
        },
        {
            id: "cryo",
            name: "Cryo",
            description: "",
            isInventory: false,
            index: 1207,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/cryo/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/cryo/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/cryo/texture"),
        },
        {
            id: "nightmare",
            name: "Nightmare",
            description: "",
            isInventory: false,
            index: 1208,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/nightmare/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/nightmare/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/nightmare/texture"),
        },
        {
            id: "arachnid",
            name: "Arachnid",
            description: "",
            isInventory: false,
            index: 1209,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/arachnid/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/arachnid/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/arachnid/texture"),
        },
        {
            id: "tarantula",
            name: "Tarantula",
            description: "",
            isInventory: false,
            index: 1210,
            next_price: 0,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/tarantula/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/tarantula/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 0,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/tarantula/texture"),
        },
        {
            id: "red",
            name: "Red",
            description: "",
            isInventory: false,
            index: 2850,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/red/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/red/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/red/texture"),
        },
        {
            id: "blue",
            name: "Blue",
            description: "",
            isInventory: false,
            index: 2900,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/blue/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/blue/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/blue/texture"),
        },
        {
            id: "black",
            name: "Black",
            description: "",
            isInventory: false,
            index: 2950,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/black/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/black/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/black/texture"),
        },
        {
            id: "white",
            name: "White",
            description: "",
            isInventory: false,
            index: 3000,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/white/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/white/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/white/texture"),
        },
        {
            id: "orange",
            name: "Orange",
            description: "",
            isInventory: false,
            index: 3050,
            next_price: 100,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/orange/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/orange/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/orange/texture"),
        },
        {
            id: "flora",
            name: "Flora",
            description: "",
            isInventory: false,
            index: 3100,
            next_price: 500,
            next_rank: 2,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/flora/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/flora/preview"),
            rank: 2,
            category: "paint",
            properts: [{"property":"SMOKY_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/flora/texture"),
        },
        {
            id: "marine",
            name: "Navy",
            description: "",
            isInventory: false,
            index: 3150,
            next_price: 500,
            next_rank: 2,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/marine/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/marine/preview"),
            rank: 2,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/marine/texture"),
        },
        {
            id: "swamp",
            name: "Swamp",
            description: "",
            isInventory: false,
            index: 3200,
            next_price: 900,
            next_rank: 3,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/swamp/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/swamp/preview"),
            rank: 3,
            category: "paint",
            properts: [{"property":"TWINS_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 900,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/swamp/texture"),
        },
        {
            id: "forester",
            name: "Forester",
            description: "",
            isInventory: false,
            index: 3250,
            next_price: 1350,
            next_rank: 4,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/forester/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/forester/preview"),
            rank: 4,
            category: "paint",
            properts: [{"property":"RAILGUN_RESISTANCE","value":"12","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 1350,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/forester/texture"),
        },
        {
            id: "safari",
            name: "Safari",
            description: "",
            isInventory: false,
            index: 3350,
            next_price: 1750,
            next_rank: 5,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/safari/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/safari/preview"),
            rank: 5,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"15","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 1750,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/safari/texture"),
        },
        {
            id: "savanna",
            name: "Savanna",
            description: "",
            isInventory: false,
            index: 3375,
            next_price: 1750,
            next_rank: 5,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/savanna/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/savanna/preview"),
            rank: 5,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 1750,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/savanna/texture"),
        },
        {
            id: "invader",
            name: "Invader",
            description: "",
            isInventory: false,
            index: 3400,
            next_price: 1750,
            next_rank: 5,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/invader/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/invader/preview"),
            rank: 5,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"15","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 1750,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/invader/texture"),
        },
        {
            id: "metallic",
            name: "Metallic",
            description: "",
            isInventory: false,
            index: 3450,
            next_price: 2100,
            next_rank: 6,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/metallic/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/metallic/preview"),
            rank: 6,
            category: "paint",
            properts: [{"property":"THUNDER_RESISTANCE","value":"18","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 2100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/metallic/texture"),
        },
        {
            id: "lava",
            name: "Lava",
            description: "",
            isInventory: false,
            index: 3500,
            next_price: 2100,
            next_rank: 6,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/lava/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/lava/preview"),
            rank: 6,
            category: "paint",
            properts: [{"property":"FREEZE_RESISTANCE","value":"18","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 2100,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/lava/texture"),
        },
        {
            id: "lead",
            name: "Lead",
            description: "",
            isInventory: false,
            index: 3600,
            next_price: 3000,
            next_rank: 8,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/lead/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/lead/preview"),
            rank: 8,
            category: "paint",
            properts: [{"property":"SHAFT_RESISTANCE","value":"25","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 3000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/lead/texture"),
        },
        {
            id: "mary",
            name: "Mary",
            description: "",
            isInventory: false,
            index: 3650,
            next_price: 6500,
            next_rank: 9,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/mary/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/mary/preview"),
            rank: 9,
            category: "paint",
            properts: [{"property":"FREEZE_RESISTANCE","value":"15","subproperties":null},{"property":"TWINS_RESISTANCE","value":"8","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"8","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 6500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/mary/texture"),
        },
        {
            id: "carbon",
            name: "Carbon",
            description: "",
            isInventory: false,
            index: 3750,
            next_price: 6500,
            next_rank: 9,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/carbon/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/carbon/preview"),
            rank: 9,
            category: "paint",
            properts: [{"property":"TWINS_RESISTANCE","value":"6","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"18","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"6","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 6500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/carbon/texture"),
        },
        {
            id: "roger",
            name: "Skull",
            description: "",
            isInventory: false,
            index: 3800,
            next_price: 12500,
            next_rank: 10,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/roger/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/roger/preview"),
            rank: 10,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"8","subproperties":null},{"property":"TWINS_RESISTANCE","value":"16","subproperties":null},{"property":"SHOTGUN_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 12500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/roger/texture"),
        },
        {
            id: "fracture",
            name: "Fracture",
            description: "",
            isInventory: false,
            index: 3850,
            next_price: 12500,
            next_rank: 10,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/fracture/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/fracture/preview"),
            rank: 10,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"10","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"8","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"16","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 12500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/fracture/texture"),
        },
        {
            id: "vortex",
            name: "Vortex",
            description: "",
            isInventory: false,
            index: 3900,
            next_price: 12500,
            next_rank: 10,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/vortex/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/vortex/preview"),
            rank: 10,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"13","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"13","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"8","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 12500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/vortex/texture"),
        },
        {
            id: "chainmail",
            name: "Chainmail",
            description: "",
            isInventory: false,
            index: 3950,
            next_price: 18500,
            next_rank: 11,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/chainmail/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/chainmail/preview"),
            rank: 11,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"22","subproperties":null},{"property":"ISIS_RESISTANCE","value":"11","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"5","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 18500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/chainmail/texture"),
        },
        {
            id: "corrosion",
            name: "Corrosion",
            description: "",
            isInventory: false,
            index: 4000,
            next_price: 18500,
            next_rank: 11,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/corrosion/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/corrosion/preview"),
            rank: 11,
            category: "paint",
            properts: [{"property":"RAILGUN_RESISTANCE","value":"10","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"15","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"15","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 18500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/corrosion/texture"),
        },
        {
            id: "tundra",
            name: "Tundra",
            description: "",
            isInventory: false,
            index: 4050,
            next_price: 18500,
            next_rank: 11,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/tundra/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/tundra/preview"),
            rank: 11,
            category: "paint",
            properts: [{"property":"SMOKY_RESISTANCE","value":"11","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"27","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 18500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/tundra/texture"),
        },
        {
            id: "alien",
            name: "Alien",
            description: "",
            isInventory: false,
            index: 4100,
            next_price: 24500,
            next_rank: 12,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/alien/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/alien/preview"),
            rank: 12,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"25","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"9","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"9","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 24500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/alien/texture"),
        },
        {
            id: "swash",
            name: "Marine",
            description: "",
            isInventory: false,
            index: 4150,
            next_price: 24500,
            next_rank: 12,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/swash/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/swash/preview"),
            rank: 12,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"10","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"18","subproperties":null},{"property":"TWINS_RESISTANCE","value":"11","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"5","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 24500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/swash/texture"),
        },
        {
            id: "pixel",
            name: "Pixel",
            description: "",
            isInventory: false,
            index: 4200,
            next_price: 30500,
            next_rank: 13,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/pixel/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/pixel/preview"),
            rank: 13,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"30","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"16","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 30500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/pixel/texture"),
        },
        {
            id: "guerrilla",
            name: "Guerrilla",
            description: "",
            isInventory: false,
            index: 4250,
            next_price: 30500,
            next_rank: 13,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/guerrilla/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/guerrilla/preview"),
            rank: 13,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"12","subproperties":null},{"property":"MACHINE_GUN_RESISTANCE","value":"26","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"8","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 30500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/guerrilla/texture"),
        },
        {
            id: "cedar",
            name: "Cedar",
            description: "",
            isInventory: false,
            index: 4300,
            next_price: 30500,
            next_rank: 13,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/cedar/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/cedar/preview"),
            rank: 13,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"8","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"30","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"8","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 30500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/cedar/texture"),
        },
        {
            id: "in_love",
            name: "In Love",
            description: "",
            isInventory: false,
            index: 4350,
            next_price: 30500,
            next_rank: 13,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/in_love/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/in_love/preview"),
            rank: 13,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"13","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"24","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 30500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/in_love/texture"),
        },
        {
            id: "desert",
            name: "Desert",
            description: "",
            isInventory: false,
            index: 4400,
            next_price: 36500,
            next_rank: 14,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/desert/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/desert/preview"),
            rank: 14,
            category: "paint",
            properts: [{"property":"TWINS_RESISTANCE","value":"8","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"26","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"8","subproperties":null},{"property":"SHOTGUN_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 36500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/desert/texture"),
        },
        {
            id: "dirty",
            name: "Mud",
            description: "",
            isInventory: false,
            index: 4450,
            next_price: 42500,
            next_rank: 15,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/dirty/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/dirty/preview"),
            rank: 15,
            category: "paint",
            properts: [{"property":"RAILGUN_RESISTANCE","value":"24","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"32","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 42500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/dirty/texture"),
        },
        {
            id: "loam",
            name: "Loam",
            description: "",
            isInventory: false,
            index: 4600,
            next_price: 50500,
            next_rank: 16,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/loam/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/loam/preview"),
            rank: 16,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"30","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"11","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"11","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"11","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 50500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/loam/texture"),
        },
        {
            id: "sakura",
            name: "Sakura",
            description: "",
            isInventory: false,
            index: 4650,
            next_price: 50500,
            next_rank: 16,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/sakura/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/sakura/preview"),
            rank: 16,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"25","subproperties":null},{"property":"MACHINE_GUN_RESISTANCE","value":"12","subproperties":null},{"property":"ISIS_RESISTANCE","value":"25","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 50500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/sakura/texture"),
        },
        {
            id: "urban",
            name: "Urban",
            description: "",
            isInventory: false,
            index: 4700,
            next_price: 63500,
            next_rank: 17,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/urban/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/urban/preview"),
            rank: 17,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"15","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"10","subproperties":null},{"property":"TWINS_RESISTANCE","value":"32","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 63500,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/urban/texture"),
        },
        {
            id: "atom",
            name: "Atom",
            description: "",
            isInventory: false,
            index: 4750,
            next_price: 76600,
            next_rank: 18,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/atom/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/atom/preview"),
            rank: 18,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"33","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"18","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"11","subproperties":null},{"property":"TWINS_RESISTANCE","value":"11","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 76600,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/atom/texture"),
        },
        {
            id: "digital",
            name: "Digital",
            description: "",
            isInventory: false,
            index: 4800,
            next_price: 76600,
            next_rank: 18,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/digital/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/digital/preview"),
            rank: 18,
            category: "paint",
            properts: [{"property":"SMOKY_RESISTANCE","value":"24","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"35","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"14","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 76600,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/digital/texture"),
        },
        {
            id: "hohloma",
            name: "Khokhloma",
            description: "",
            isInventory: false,
            index: 4850,
            next_price: 76600,
            next_rank: 18,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/hohloma/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/hohloma/preview"),
            rank: 18,
            category: "paint",
            properts: [{"property":"FREEZE_RESISTANCE","value":"22","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"30","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"22","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 76600,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/hohloma/texture"),
        },
        {
            id: "electra",
            name: "Electra",
            description: "",
            isInventory: false,
            index: 4950,
            next_price: 90000,
            next_rank: 19,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/electra/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/electra/preview"),
            rank: 19,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"38","subproperties":null},{"property":"TWINS_RESISTANCE","value":"20","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"20","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 90000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/electra/texture"),
        },
        {
            id: "cherry",
            name: "Cherry",
            description: "",
            isInventory: false,
            index: 5000,
            next_price: 103000,
            next_rank: 20,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/cherry/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/cherry/preview"),
            rank: 20,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"22","subproperties":null},{"property":"TWINS_RESISTANCE","value":"34","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"28","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 103000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/cherry/texture"),
        },
        {
            id: "blacksmith",
            name: "Blacksmith",
            description: "",
            isInventory: false,
            index: 5050,
            next_price: 103000,
            next_rank: 20,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/blacksmith/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/blacksmith/preview"),
            rank: 20,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"40","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"18","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"26","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 103000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/blacksmith/texture"),
        },
        {
            id: "rustle",
            name: "Rustle",
            description: "",
            isInventory: false,
            index: 5100,
            next_price: 103000,
            next_rank: 20,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/rustle/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/rustle/preview"),
            rank: 20,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"15","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"30","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"40","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 103000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/rustle/texture"),
        },
        {
            id: "python",
            name: "Python",
            description: "",
            isInventory: false,
            index: 5150,
            next_price: 103000,
            next_rank: 20,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/python/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/python/preview"),
            rank: 20,
            category: "paint",
            properts: [{"property":"FREEZE_RESISTANCE","value":"44","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"40","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 103000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/python/texture"),
        },
        {
            id: "sandstone",
            name: "Sandstone",
            description: "",
            isInventory: false,
            index: 5200,
            next_price: 116000,
            next_rank: 21,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/sandstone/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/sandstone/preview"),
            rank: 21,
            category: "paint",
            properts: [{"property":"TWINS_RESISTANCE","value":"12","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"22","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"34","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"22","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 116000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/sandstone/texture"),
        },
        {
            id: "spark",
            name: "Spark",
            description: "",
            isInventory: false,
            index: 5250,
            next_price: 116000,
            next_rank: 21,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/spark/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/spark/preview"),
            rank: 21,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"30","subproperties":null},{"property":"TWINS_RESISTANCE","value":"18","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"42","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 116000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/spark/texture"),
        },
        {
            id: "winter",
            name: "Winter",
            description: "",
            isInventory: false,
            index: 5300,
            next_price: 129000,
            next_rank: 22,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/winter/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/winter/preview"),
            rank: 22,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"12","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"26","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"12","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"45","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 129000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/winter/texture"),
        },
        {
            id: "needle",
            name: "Needle",
            description: "",
            isInventory: false,
            index: 5350,
            next_price: 180000,
            next_rank: 24,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/needle/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/needle/preview"),
            rank: 24,
            category: "paint",
            properts: [{"property":"RICOCHET_RESISTANCE","value":"22","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"50","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"28","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 180000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/needle/texture"),
        },
        {
            id: "zeus",
            name: "Zeus",
            description: "",
            isInventory: false,
            index: 5400,
            next_price: 180000,
            next_rank: 24,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/zeus/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/zeus/preview"),
            rank: 24,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"50","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"25","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"25","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 180000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/zeus/texture"),
        },
        {
            id: "hive",
            name: "Hive",
            description: "",
            isInventory: false,
            index: 5450,
            next_price: 192000,
            next_rank: 25,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/hive/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/hive/preview"),
            rank: 25,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"42","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"26","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"32","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 192000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/hive/texture"),
        },
        {
            id: "rock",
            name: "Rock",
            description: "",
            isInventory: false,
            index: 5500,
            next_price: 192000,
            next_rank: 25,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/rock/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/rock/preview"),
            rank: 25,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"28","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"12","subproperties":null},{"property":"TWINS_RESISTANCE","value":"50","subproperties":null},{"property":"SHOTGUN_RESISTANCE","value":"10","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 192000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/rock/texture"),
        },
        {
            id: "mars",
            name: "Mars",
            description: "",
            isInventory: false,
            index: 5550,
            next_price: 204000,
            next_rank: 26,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/mars/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/mars/preview"),
            rank: 26,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"50","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"30","subproperties":null},{"property":"ISIS_RESISTANCE","value":"20","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 204000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/mars/texture"),
        },
        {
            id: "prodigi",
            name: "Prodigy",
            description: "",
            isInventory: false,
            index: 5600,
            next_price: 204000,
            next_rank: 26,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/prodigi/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/prodigi/preview"),
            rank: 26,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"7","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"23","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"50","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"20","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 204000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/prodigi/texture"),
        },
        {
            id: "graffiti",
            name: "Graffiti",
            description: "",
            isInventory: false,
            index: 5650,
            next_price: 216000,
            next_rank: 27,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/graffiti/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/graffiti/preview"),
            rank: 27,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"50","subproperties":null},{"property":"TWINS_RESISTANCE","value":"25","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"25","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 216000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/graffiti/texture"),
        },
        {
            id: "mirage",
            name: "Mirage",
            description: "",
            isInventory: false,
            index: 5653,
            next_price: 216000,
            next_rank: 27,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/mirage/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/mirage/preview"),
            rank: 27,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"35","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"22","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"20","subproperties":null},{"property":"MACHINE_GUN_RESISTANCE","value":"23","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 216000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/mirage/texture"),
        },
        {
            id: "irbis",
            name: "Irbis",
            description: "",
            isInventory: false,
            index: 5700,
            next_price: 216000,
            next_rank: 27,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/irbis/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/irbis/preview"),
            rank: 27,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"50","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"27","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"23","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 216000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/irbis/texture"),
        },
        {
            id: "emerald",
            name: "Emerald",
            description: "",
            isInventory: false,
            index: 5750,
            next_price: 228000,
            next_rank: 28,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/emerald/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/emerald/preview"),
            rank: 28,
            category: "paint",
            properts: [{"property":"TWINS_RESISTANCE","value":"35","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"50","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"15","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 228000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/emerald/texture"),
        },
        {
            id: "inferno",
            name: "Inferno",
            description: "",
            isInventory: false,
            index: 5800,
            next_price: 228000,
            next_rank: 28,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/inferno/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/inferno/preview"),
            rank: 28,
            category: "paint",
            properts: [{"property":"FIREBIRD_RESISTANCE","value":"36","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"50","subproperties":null},{"property":"TWINS_RESISTANCE","value":"14","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 228000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/inferno/texture"),
        },
        {
            id: "nano",
            name: "Nano",
            description: "",
            isInventory: false,
            index: 5850,
            next_price: 240000,
            next_rank: 29,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/nano/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/nano/preview"),
            rank: 29,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"35","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"32","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"22","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"11","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 240000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/nano/texture"),
        },
        {
            id: "raccoon",
            name: "Raccoon",
            description: "",
            isInventory: false,
            index: 5900,
            next_price: 240000,
            next_rank: 29,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/raccoon/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/raccoon/preview"),
            rank: 29,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"33","subproperties":null},{"property":"MACHINE_GUN_RESISTANCE","value":"27","subproperties":null},{"property":"ISIS_RESISTANCE","value":"19","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"21","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 240000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/raccoon/texture"),
        },
        {
            id: "clay",
            name: "Clay",
            description: "",
            isInventory: false,
            index: 5950,
            next_price: 240000,
            next_rank: 29,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/clay/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/clay/preview"),
            rank: 29,
            category: "paint",
            properts: [{"property":"RICOCHET_RESISTANCE","value":"50","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"20","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"30","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 240000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/clay/texture"),
        },
        {
            id: "taiga",
            name: "Taiga",
            description: "",
            isInventory: false,
            index: 6000,
            next_price: 240000,
            next_rank: 29,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/taiga/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/taiga/preview"),
            rank: 29,
            category: "paint",
            properts: [{"property":"ISIS_RESISTANCE","value":"35","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"24","subproperties":null},{"property":"TWINS_RESISTANCE","value":"17","subproperties":null},{"property":"RICOCHET_RESISTANCE","value":"24","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 240000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/taiga/texture"),
        },
        {
            id: "tiger",
            name: "Tiger",
            description: "",
            isInventory: false,
            index: 6050,
            next_price: 250000,
            next_rank: 30,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/tiger/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/tiger/preview"),
            rank: 30,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"47","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"35","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"18","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 250000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/tiger/texture"),
        },
        {
            id: "jade",
            name: "Jade",
            description: "",
            isInventory: false,
            index: 6100,
            next_price: 250000,
            next_rank: 30,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/jade/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/jade/preview"),
            rank: 30,
            category: "paint",
            properts: [{"property":"THUNDER_RESISTANCE","value":"11","subproperties":null},{"property":"SMOKY_RESISTANCE","value":"24","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"50","subproperties":null},{"property":"SHOTGUN_RESISTANCE","value":"15","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 250000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/jade/texture"),
        },
        {
            id: "picasso",
            name: "Picasso",
            description: "",
            isInventory: false,
            index: 6150,
            next_price: 250000,
            next_rank: 30,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/picasso/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/picasso/preview"),
            rank: 30,
            category: "paint",
            properts: [{"property":"FREEZE_RESISTANCE","value":"20","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"20","subproperties":null},{"property":"RAILGUN_RESISTANCE","value":"27","subproperties":null},{"property":"SHAFT_RESISTANCE","value":"33","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 250000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/picasso/texture"),
        },
        {
            id: "lumberjack",
            name: "Lumberjack",
            description: "",
            isInventory: false,
            index: 6200,
            next_price: 250000,
            next_rank: 30,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/lumberjack/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/lumberjack/preview"),
            rank: 30,
            category: "paint",
            properts: [{"property":"MACHINE_GUN_RESISTANCE","value":"10","subproperties":null},{"property":"ISIS_RESISTANCE","value":"30","subproperties":null},{"property":"FIREBIRD_RESISTANCE","value":"30","subproperties":null},{"property":"FREEZE_RESISTANCE","value":"30","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 250000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/lumberjack/texture"),
        },
        {
            id: "africa",
            name: "Africa",
            description: "",
            isInventory: false,
            index: 6250,
            next_price: 250000,
            next_rank: 30,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/africa/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/africa/preview"),
            rank: 30,
            category: "paint",
            properts: [{"property":"SHOTGUN_RESISTANCE","value":"20","subproperties":null},{"property":"MACHINE_GUN_RESISTANCE","value":"30","subproperties":null},{"property":"TWINS_RESISTANCE","value":"25","subproperties":null},{"property":"THUNDER_RESISTANCE","value":"25","subproperties":null}],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 250000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/africa/texture"),
        },
        {
            id: "acid",
            name: "Acid",
            description: "",
            isInventory: false,
            index: 6300,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/acid/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/acid/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/acid/texture"),
        },
        {
            id: "champion",
            name: "Champion",
            description: "",
            isInventory: false,
            index: 6350,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/champion/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/champion/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/champion/texture"),
        },
        {
            id: "impulse",
            name: "Impulse",
            description: "",
            isInventory: false,
            index: 6400,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/impulse/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/impulse/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/impulse/texture"),
        },
        {
            id: "frost",
            name: "Frost",
            description: "",
            isInventory: false,
            index: 6450,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/frost/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/frost/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/frost/texture"),
        },
        {
            id: "star",
            name: "Star",
            description: "",
            isInventory: false,
            index: 6500,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/star/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/star/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/star/texture"),
        },
        {
            id: "bronze",
            name: "Bronze",
            description: "",
            isInventory: false,
            index: 6550,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/bronze/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/bronze/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/bronze/texture"),
        },
        {
            id: "silver",
            name: "Silver",
            description: "",
            isInventory: false,
            index: 6600,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/silver/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/silver/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/silver/texture"),
        },
        {
            id: "veteran",
            name: "Veteran",
            description: "",
            isInventory: false,
            index: 6650,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/veteran/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/veteran/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/veteran/texture"),
        },
        {
            id: "gladiator",
            name: "Gladiator",
            description: "",
            isInventory: false,
            index: 6700,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/gladiator/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/gladiator/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/gladiator/texture"),
        },
        {
            id: "helper",
            name: "Helper",
            description: "",
            isInventory: false,
            index: 6800,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/helper/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/helper/preview"),
            rank: 1,
            category: "paint",
            properts: [{ property: "ALL_RESISTANCE", value: "30", subproperties: null }],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/helper/texture"),
        },
        {
            id: "visual_disruptor",
            name: "Visual Disruptor",
            description: "",
            isInventory: false,
            index: 6850,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/visual_disruptor/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/visual_disruptor/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/visual_disruptor/texture"),
        },
        {
            id: "tesseract_camo",
            name: "Tesseract Camo",
            description: "",
            isInventory: false,
            index: 6900,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/tesseract_camo/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/tesseract_camo/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/tesseract_camo/texture"),
        },
        {
            id: "symbiote",
            name: "Symbiote",
            description: "",
            isInventory: false,
            index: 6950,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/symbiote/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/symbiote/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/symbiote/texture"),
        },
        {
            id: "spinner",
            name: "Spinner",
            description: "",
            isInventory: false,
            index: 7000,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/spinner/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/spinner/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/spinner/texture"),
        },
        {
            id: "galaxy",
            name: "Galaxy",
            description: "",
            isInventory: false,
            index: 7050,
            next_price: 10000,
            next_rank: 1,
            type: 3,
            baseItemId: () => ResourceManager.getIdlowById("paint/galaxy/preview"),
            previewResourceId: () => ResourceManager.getIdlowById("paint/galaxy/preview"),
            rank: 1,
            category: "paint",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 10000,
            remainingTimeInSec: -1,
            coloring: () => ResourceManager.getIdlowById("paint/galaxy/texture"),
        },
    ],
    // Supplies (consumables). category "inventory", type 4. previewResourceId/baseItemId are the
    // client's built-in inventory icon ids (small fixed numbers), not CDN resource idLows. The 5
    // consumables are owned in quantity (shown in the depot with a `count`); "1000_scores" is
    // consumed instantly on purchase and grants experience (rank points) instead of stacking.
    supplies: [
        { id: "health", name: "Repair Kit", description: "", index: 7600, type: 4, rank: 3, price: 150 },
        { id: "armor", name: "Double Armor", description: "", index: 7650, type: 4, rank: 4, price: 50 },
        { id: "double_damage", name: "Double Damage", description: "", index: 7700, type: 4, rank: 4, price: 50 },
        { id: "n2o", name: "Speed Boost", description: "", index: 7750, type: 4, rank: 4, price: 50 },
        { id: "mine", name: "Mine", description: "", index: 7800, type: 4, rank: 5, price: 50 },
        { id: "1000_scores", name: "1000 Experience", description: "", index: 7550, type: 4, rank: 11, price: 2000, instantScore: 1000 },
    ],
    // Kits (bundle purchases). Grants multiple items when bought; shown in the garage market before passes.
    kits: [
        {
            id: "mosquito",
            name: "Mosquito Kit",
            description: "Grants Railgun M2, Wasp M2, and Savanna paint.",
            isInventory: false,
            index: 7850,
            next_price: 110000,
            next_rank: 15,
            type: 5,
            baseItemId: () => ResourceManager.getIdlowById("kits/mosquito/preview"),
            previewResource: "kits/mosquito/preview" as ResourceId,
            previewResourceId: () => ResourceManager.getIdlowById("kits/mosquito/preview"),
            rank: 15,
            category: "kit",
            properts: [],
            discount: { percent: 0, timeLeftInSeconds: -1751858089, timeToStartInSeconds: -1751858089 },
            grouped: false,
            isForRent: false,
            price: 110000,
            remainingTimeInSec: -1,
            grants: { turret: "railgun", turretMod: 2, hull: "wasp", hullMod: 2, paint: "sandstone" },
        },
    ],
    // Passes/assinaturas (category "special", type 5). baseItemId/previewResourceId = ícones internos do
    // client (números pequenos fixos, como os supplies). Comprar ESTENDE a expiração do passe no user
    // (`expiresField`), não empilha item. `newbie` (price -1) é concedido na criação de conta e aparece no
    // depósito enquanto ativo; `up_score` é comprável no mercado.
    passes: [
        { id: "newbie", name: "Newbie Pass", description: "", index: 7900, type: 5, rank: 1, price: -1, category: "special", durationMs: NEWBIE_DURATION_MS, expiresField: "newbieExpiresAt" },
        { id: "up_score", name: "Score Multiplier Pass", description: "", index: 8000, type: 5, rank: 1, price: 12500, category: "special", durationMs: UP_SCORE_DURATION_MS, expiresField: "upScoreExpiresAt" },
        { id: "pro_battle", name: "PRO Battle Pass", description: "", index: 8200, type: 5, rank: 1, price: 139, category: "special", durationMs: PRO_BATTLE_DURATION_MS, expiresField: "proBattleExpiresAt", priceByRank: PRO_BATTLE_PRICE_BY_RANK },
        // Card "Dobro de cristais" (double_crystalls): NÃO comprável na garagem (price -1) — só aparece no
        // depósito, com o tempo de validade, enquanto ativo (dura 24h). Dobra os cristais de DOAÇÕES no
        // shop (não os ganhos em jogo). id/index/preview/descrição espelham o oficial (captura s6-54824).
        { id: "double_crystalls", name: "Double Crystals", description: "", index: 8150, type: 5, rank: 1, price: -1, category: "special", durationMs: 0, expiresField: "crystalAbonementExpiresAt" },
    ],
};