package §5214235122235135123423632234§
{
   public class §521423842397123423632234§
   {
      
      public static const TEXT_FRIENDS_EXIT_FROM_BATTLE_ALERT:String = "TEXT_FRIENDS_EXIT_FROM_BATTLE_ALERT";
      
      public static const TEXT_TEAM_KICK_COMPLAINT_SENT:String = "TEXT_TEAM_KICK_COMPLAINT_SENT";
      
      public static const STRING_PARTNER_HELP_PANEL_BUTTON_BAR_HELPER_TEXT:String = "STRING_PARTNER_HELP_PANEL_BUTTON_BAR_HELPER_TEXT";
      
      public static const STRING_HELP_PANEL_BUTTON_BAR_HELPER_TEXT:String = "STRING_HELP_PANEL_BUTTON_BAR_HELPER_TEXT";
      
      public static const STRING_HELP_PANEL_BUTTON_BAR_HELPER_ARROW_LENGTH:String = "STRING_HELP_PANEL_BUTTON_BAR_HELPER_ARROW_LENGTH";
      
      public static const STRING_HELP_PANEL_RANK_BAR_HELPER_TEXT:String = "STRING_HELP_PANEL_RANK_BAR_HELPER_TEXT";
      
      public static const STRING_HELP_PANEL_RANK_BAR_HELPER_ARROW_LENGTH:String = "STRING_HELP_PANEL_RANK_BAR_HELPER_ARROW_LENGTH";
      
      public static const STRING_HELP_PANEL_RATING_INDICATOR_HELPER_TEXT:String = "STRING_HELP_PANEL_RATING_INDICATOR_HELPER_TEXT";
      
      public static const STRING_HELP_PANEL_RATING_INDICATOR_HELPER_ARROW_LENGTH:String = "STRING_HELP_PANEL_RATING_INDICATOR_HELPER_ARROW_LENGTH";
      
      public static const STRING_HELP_PANEL_MAIN_MENU_HELPER_TEXT:String = "STRING_HELP_PANEL_MAIN_MENU_HELPER_TEXT";
      
      public static const STRING_HELP_PANEL_MAIN_MENU_HELPER_ARROW_LENGTH:String = "STRING_HELP_PANEL_MAIN_MENU_HELPER_ARROW_LENGTH";
      
      public static const STRING_HELP_PANEL_MONEY_HELPER_TEXT:String = "STRING_HELP_PANEL_MONEY_HELPER_TEXT";
      
      public static const STRING_HELP_PANEL_MONEY_HELPER_ARROW_LENGTH:String = "STRING_HELP_PANEL_MONEY_HELPER_ARROW_LENGTH";
      
      public static const STRING_HELP_PANEL_SCORE_HELPER_TEXT:String = "STRING_HELP_PANEL_SCORE_HELPER_TEXT";
      
      public static const STRING_HELP_PANEL_SCORE_HELPER_ARROW_LENGTH:String = "STRING_HELP_PANEL_SCORE_HELPER_ARROW_LENGTH";
      
      public static const STRING_HELP_PANEL_RANK_HELPER_TEXT:String = "STRING_HELP_PANEL_RANK_HELPER_TEXT";
      
      public static const STRING_HELP_PANEL_RANK_HELPER_ARROW_LENGTH:String = "STRING_HELP_PANEL_RANK_HELPER_ARROW_LENGTH";
      
      public static const TEXT_KEYBOARD_KEY_LEFT:String = "TEXT_KEYBOARD_KEY_LEFT";
      
      public static const TEXT_KEYBOARD_KEY_RIGHT:String = "TEXT_KEYBOARD_KEY_RIGHT";
      
      public static const TEXT_KEYBOARD_KEY_UP:String = "TEXT_KEYBOARD_KEY_UP";
      
      public static const TEXT_KEYBOARD_KEY_DOWN:String = "TEXT_KEYBOARD_KEY_DOWN";
      
      public static const TEXT_KEYBOARD_KEY_PG_DN:String = "TEXT_KEYBOARD_KEY_PG_DN";
      
      public static const TEXT_KEYBOARD_KEY_PG_UP:String = "TEXT_KEYBOARD_KEY_PG_UP";
      
      public static const TEXT_KEYBOARD_KEY_SPACE:String = "TEXT_KEYBOARD_KEY_SPACE";
      
      public static const TEXT_SPECTATOR_NAME:String = "TEXT_SPECTATOR_NAME";
      
      public static const STRING_MAIN_PANEL_UPDATE_RANK_NOTICE:String = "STRING_MAIN_PANEL_UPDATE_RANK_NOTICE";
      
      public static const STRING_MAIN_PANEL_UPDATE_RANK_NOTICE_GIFT:String = "STRING_MAIN_PANEL_UPDATE_RANK_NOTICE_GIFT";
      
      public static const TEXT_GARAGE_NEW_ITEMS_ALERT:String = "TEXT_GARAGE_NEW_ITEMS_ALERT";
      
      public static const TEXT_REARM_SELFDISTRUCTION:String = "TEXT_REARM_SELFDISTRUCTION";
      
      public static const TEXT_PREMIUM_ALERT_RETURN:String = "TEXT_PREMIUM_ALERT_RETURN";
      
      public static const TEXT_PREMIUM_ALERT_WELCOM:String = "TEXT_PREMIUM_ALERT_WELCOM";
      
      public static const TEXT_PREMIUM_NOTIFICATION_COMPLETE:String = "TEXT_PREMIUM_NOTIFICATION_COMPLETE";
      
      public static const TEXT_PREMIUM_NOTIFICATION_SOON_COMPLETE:String = "TEXT_PREMIUM_NOTIFICATION_SOON_COMPLETE";
      
      public static const TEXT_PREMIUM_BUTTON_EXTEND:String = "TEXT_PREMIUM_BUTTON_EXTEND";
      
      public static const TEXT_NEW_PRESENTS_ALERT_ACCEPT_BUTTON:String = "TEXT_NEW_PRESENTS_ALERT_ACCEPT_BUTTON";
      
      public static const TEXT_SEND_PRESENT_BUTTON:String = "TEXT_SEND_PRESENT_BUTTON";
      
      public static const TEXT_PRESENT_RECIPIENT_NAME:String = "TEXT_PRESENT_RECIPIENT_NAME";
      
      public static const TEXT_TYPE_MESSAGE_WITH_PRESENT:String = "TEXT_TYPE_MESSAGE_WITH_PRESENT";
      
      public static const STRING_GARAGE_CATEGORY_BUTTON_SPECIAL:String = "STRING_GARAGE_CATEGORY_BUTTON_SPECIAL";
      
      public static const STRING_GARAGE_CATEGORY_BUTTON_TURRETS:String = "STRING_GARAGE_CATEGORY_BUTTON_TURRETS";
      
      public static const STRING_GARAGE_CATEGORY_BUTTON_HULLS:String = "STRING_GARAGE_CATEGORY_BUTTON_HULLS";
      
      public static const STRING_GARAGE_CATEGORY_BUTTON_PAINTS:String = "STRING_GARAGE_CATEGORY_BUTTON_PAINTS";
      
      public static const STRING_GARAGE_CATEGORY_BUTTON_KITS:String = "STRING_GARAGE_CATEGORY_BUTTON_KITS";
      
      public static const STRING_GARAGE_CATEGORY_BUTTON_SUPPLIES:String = "STRING_GARAGE_CATEGORY_BUTTON_SUPPLIES";
      
      public static const STRING_GARAGE_CATEGORY_BUTTON_RESISTANCE_MODULES:String = "STRING_GARAGE_CATEGORY_BUTTON_RESISTANCE_MODULES";
      
      public static const STRING_GARAGE_CATEGORY_BUTTON_PRESENTS:String = "STRING_GARAGE_CATEGORY_BUTTON_PRESENTS";
      
      public static const STRING_DONATION_ALERT_DONATED_CRYSTALS_TEXT:String = "STRING_DONATION_ALERT_DONATED_CRYSTALS_TEXT";
      
      public static const STRING_DONATION_ALERT_PACKAGE_BONUS_CRYSTALS_TEXT:String = "STRING_DONATION_ALERT_PACKAGE_BONUS_CRYSTALS_TEXT";
      
      public static const STRING_DONATION_ALERT_DOUBLE_CRYSTAL_CRYSTALS_TEXT:String = "STRING_DONATION_ALERT_DOUBLE_CRYSTAL_CRYSTALS_TEXT";
      
      public static const STRING_DONATION_ALERT_RECEIVED_CRYSTALS_TEXT:String = "STRING_DONATION_ALERT_RECEIVED_CRYSTALS_TEXT";
      
      public static const STRING_FREE_UIDS_FORM_HEADER:String = "STRING_FREE_UIDS_FORM_HEADER";
      
      public static const STRING_VKONTAKTE_NAME:String = "STRING_VKONTAKTE_NAME";
      
      public static const STRING_PARTNER_REGISTARTION_FORM_CHOOSE_NAME_TEXT:String = "STRING_PARTNER_REGISTARTION_FORM_CHOOSE_NAME_TEXT";
      
      public static const STRING_PARTNER_REGISTARTION_FORM_CONTINUE:String = "STRING_PARTNER_REGISTARTION_FORM_CONTINUE";
      
      public static const STRING_BACK_BUTTON:String = "STRING_BACK_BUTTON";
      
      public static const STRING_PARTNER_REGISTARTION_FORM_AGREEMENT_NOTE_TEXT:String = "STRING_PARTNER_REGISTARTION_FORM_AGREEMENT_NOTE_TEXT";
      
      public static const STRING_GAME_RULES:String = "STRING_GAME_RULES";
      
      public static const STRING_GAME_TERMS:String = "STRING_GAME_TERMS";
      
      public static const STRING_GAME_PRIVACY_POLICY:String = "STRING_GAME_PRIVACY_POLICY";
      
      public static const STRING_COMPLETE_BUTTON:String = "STRING_COMPLETE_BUTTON";
      
      public static const STRING_LINK_EXTERNAL_LOGIN_FORM_ADVICE:String = "STRING_LINK_EXTERNAL_LOGIN_FORM_ADVICE";
      
      public static const STRING_CHECK_PASSWORD_FORM_BUTTON_NEW_PLAYER_TEXT:String = "STRING_CHECK_PASSWORD_FORM_BUTTON_NEW_PLAYER_TEXT";
      
      public static const STRING_CHECK_PASSWORK_FORM_LOGIN_VIA:String = "STRING_CHECK_PASSWORK_FORM_LOGIN_VIA";
      
      public static const STRING_REGISTER_FORM_SKIP_REGISTRATION_TEXT:String = "STRING_REGISTER_FORM_SKIP_REGISTRATION_TEXT";
      
      public static const STRING_REGISTER_FORM_TITLE_SKIP_REGISTRATION_TEXT:String = "STRING_REGISTER_FORM_TITLE_SKIP_REGISTRATION_TEXT";
      
      public static const STRING_REGISTER_FORM_TO_LOGIN_PAGE_TEXT:String = "STRING_REGISTER_FORM_TO_LOGIN_PAGE_TEXT";
      
      public static const STRING_REGISTER_FORM_REGISTER_VIA:String = "STRING_REGISTER_FORM_REGISTER_VIA";
      
      public static const STRING_YOU_WERE_KICKED_LOGIN_TEXT:String = "STRING_YOU_WERE_KICKED_LOGIN_TEXT";
      
      public static const STRING_ALERT_ERROR_EXTERNAL_ENTER:String = "STRING_ALERT_ERROR_EXTERNAL_ENTER";
      
      public static const STRING_ALERT_GAME_ACCOUNT_ALREADY_LINKED:String = "STRING_ALERT_GAME_ACCOUNT_ALREADY_LINKED";
      
      public static const STRING_CAPTCHA_FORM_TITLE:String = "STRING_CAPTCHA_FORM_TITLE";
      
      public static const ACCOUNT_RECOVERY_FORM_ENTER_CODE:String = "ACCOUNT_RECOVERY_FORM_ENTER_CODE";
      
      public static const ACCOUNT_RECOVERY_FORM_NEW_PASSWORD:String = "ACCOUNT_RECOVERY_FORM_NEW_PASSWORD";
      
      public static const ACCOUNT_RECOVERY_FORM_SAVE:String = "ACCOUNT_RECOVERY_FORM_SAVE";
      
      public static const ACCOUNT_RECOVERY_FORM_CANCEL:String = "ACCOUNT_RECOVERY_FORM_CANCEL";
      
      public static const STRING_CAPTCHA_PROCEED_BUTTON:String = "STRING_CAPTCHA_PROCEED_BUTTON";
      
      public static const REGISTER_FORM_HEADER_TEXT:String = "REGISTER_FORM_HEADER_TEXT";
      
      public static const REGISTER_FORM_CALLSIGN_INPUT_LABEL_TEXT:String = "REGISTER_FORM_CALLSIGN_INPUT_LABEL_TEXT";
      
      public static const REGISTER_FORM_PASSWORD_INPUT_LABEL_TEXT:String = "REGISTER_FORM_PASSWORD_INPUT_LABEL_TEXT";
      
      public static const REGISTER_FORM_REPEAT_PASSWORD_INPUT_LABEL_TEXT:String = "REGISTER_FORM_REPEAT_PASSWORD_INPUT_LABEL_TEXT";
      
      public static const REGISTER_FORM_REMEMBER_ME_CHECKBOX_LABEL_TEXT:String = "REGISTER_FORM_REMEMBER_ME_CHECKBOX_LABEL_TEXT";
      
      public static const REGISTER_FORM_AGREEMENT_NOTE_TEXT:String = "REGISTER_FORM_AGREEMENT_NOTE_TEXT";
      
      public static const REGISTER_FORM_AGREEMENT_CHECKBOX_LABEL_TEXT:String = "REGISTER_FORM_AGREEMENT_CHECKBOX_LABEL_TEXT";
      
      public static const REGISTER_FORM_EMAIL_LABEL_TEXT:String = "REGISTER_FORM_EMAIL_LABEL_TEXT";
      
      public static const REGISTER_FORM_CONFIRM_TEXT:String = "REGISTER_FORM_CONFIRM_TEXT";
      
      public static const REGISTER_FORM_SEND_NEWS_TEXT:String = "REGISTER_FORM_SEND_NEWS_TEXT";
      
      public static const STRING_ERROR_EMAIL_INVALID:String = "STRING_ERROR_EMAIL_INVALID";
      
      public static const STRING_HELP_NAME_IS_FORBIDDEN:String = "STRING_HELP_NAME_IS_FORBIDDEN";
      
      public static const STRING_HELP_NAME_IS_NOT_UNIQUE:String = "STRING_HELP_NAME_IS_NOT_UNIQUE";
      
      public static const STRING_HELP_PASSWORD_IS_TOO_SIMPLE:String = "STRING_HELP_PASSWORD_IS_TOO_SIMPLE";
      
      public static const STRING_HELP_PASSWORDS_DO_NOT_MATCH:String = "STRING_HELP_PASSWORDS_DO_NOT_MATCH";
      
      public static const STRING_ERROR_EMAIL_NOT_UNIQUE:String = "STRING_ERROR_EMAIL_NOT_UNIQUE";
      
      public static const STRING_ERROR_EMAIL_DOMAIN_IS_FORBIDDEN:String = "STRING_ERROR_EMAIL_DOMAIN_IS_FORBIDDEN";
      
      public static const STRING_HELP_SYMBOL_IS_NOT_ALLOWED:String = "STRING_HELP_SYMBOL_IS_NOT_ALLOWED";
      
      public static const STRING_ALERT_ACCOUNT_CANT_BE_UNLINKED:String = "STRING_ALERT_ACCOUNT_CANT_BE_UNLINKED";
      
      public static const MAIN_PANEL_RATING_LABEL:String = "MAIN_PANEL_RATING_LABEL";
      
      public static const MAIN_PANEL_BUTTON_BATTLES:String = "MAIN_PANEL_BUTTON_BATTLES";
      
      public static const MAIN_PANEL_BUTTON_GARAGE:String = "MAIN_PANEL_BUTTON_GARAGE";
      
      public static const MAIN_PANEL_BUTTON_FRIENDS:String = "MAIN_PANEL_BUTTON_FRIENDS";
      
      public static const MAIN_PANEL_BUTTON_DONATE:String = "MAIN_PANEL_BUTTON_DONATE";
      
      public static const STRING_DISABLED_CHAT_LABEL_TEXT:String = "STRING_DISABLED_CHAT_LABEL_TEXT";
      
      public static const STRING_TYPING_SPEED_BANNED:String = "STRING_TYPING_SPEED_BANNED";
      
      public static const TEXT_BATTLE_CREATE_PANEL_FLOOD_ALERT_TEXT:String = "TEXT_BATTLE_CREATE_PANEL_FLOOD_ALERT_TEXT";
      
      public static const STRING_SETTINGS_MOUSE_CONTROL_CHECKBOX:String = "STRING_SETTINGS_MOUSE_CONTROL_CHECKBOX";
      
      public static const STRING_INVITE_TO_BATTLE_LABEL:String = "STRING_INVITE_TO_BATTLE_LABEL";
      
      public static const STRING_IS_CONSIDERING_YOUR_INVITE_LABEL:String = "STRING_IS_CONSIDERING_YOUR_INVITE_LABEL";
      
      public static const STRING_INVITES_YOU_TO_A_BATTLE_LABEL:String = "STRING_INVITES_YOU_TO_A_BATTLE_LABEL";
      
      public static const STRING_THERE_ARE_PLACES_AVAILABLE_LABEL:String = "STRING_THERE_ARE_PLACES_AVAILABLE_LABEL";
      
      public static const STRING_NO_PLACES_AVAILABLE_LABEL:String = "STRING_NO_PLACES_AVAILABLE_LABEL";
      
      public static const STRING_BATTLE_IS_UNAVAILABLE_AT_YOUR_RANK_LABEL:String = "STRING_BATTLE_IS_UNAVAILABLE_AT_YOUR_RANK_LABEL";
      
      public static const STRING_SERVER_LABEL:String = "STRING_SERVER_LABEL";
      
      public static const STRING_BATTLE_CANNOT_BE_FOUND_LABEL:String = "STRING_BATTLE_CANNOT_BE_FOUND_LABEL";
      
      public static const STRING_ALERT_INVITE_TO_BATTLE_IS_UNAVAILABLE_RANK:String = "STRING_ALERT_INVITE_TO_BATTLE_IS_UNAVAILABLE_RANK";
      
      public static const STRING_BATTLE_CANNOT_BE_FOUND_ALERT:String = "STRING_BATTLE_CANNOT_BE_FOUND_ALERT";
      
      public static const STRING_GO_TO_BATTLE_LABEL:String = "STRING_GO_TO_BATTLE_LABEL";
      
      public static const STRING_DECLINE_LABEL:String = "STRING_DECLINE_LABEL";
      
      public static const STRING_YOUR_ARE_PLAING_SAFP_ALERT:String = "STRING_YOUR_ARE_PLAING_SAFP_ALERT";
      
      public static const STRING_IS_JOINING_THE_BATTLE_AT_YOUR_INVITATION_LABEL:String = "STRING_IS_JOINING_THE_BATTLE_AT_YOUR_INVITATION_LABEL";
      
      public static const STRING_REFUSED_TO_JOIN_THE_BATTLE_AT_YOUR_INVITATION_LABEL:String = "STRING_REFUSED_TO_JOIN_THE_BATTLE_AT_YOUR_INVITATION_LABEL";
      
      public static const STRING_YOUR_FRIEND_DISABLED_INVITES_LABEL:String = "STRING_YOUR_FRIEND_DISABLED_INVITES_LABEL";
      
      public static const STRING_YOUR_FRIEND_IS_ENTERING_THE_GAME_LABEL:String = "STRING_YOUR_FRIEND_IS_ENTERING_THE_GAME_LABEL";
      
      public static const STRING_YOUR_FRIEND_IS_ALREADY_IN_THIS_BATTLE_LABEL:String = "STRING_YOUR_FRIEND_IS_ALREADY_IN_THIS_BATTLE_LABEL";
      
      public static const STRING_YOUR_FRIEND_IS_OFFLINE_LABEL:String = "STRING_YOUR_FRIEND_IS_OFFLINE_LABEL";
      
      public static const STRING_ONLINE_LABEL:String = "STRING_ONLINE_LABEL";
      
      public static const STRING_OFFLINE_LABEL:String = "STRING_OFFLINE_LABEL";
      
      public static const STRING_ALERT_GOT_TO_BATTLE_IS_UNAVAILABLE_RANK:String = "STRING_ALERT_GOT_TO_BATTLE_IS_UNAVAILABLE_RANK";
      
      public static const STRING_ALERT_GO_TO_BATTLE_IS_UNAVAILABLE_RANK_FUND:String = "STRING_ALERT_GO_TO_BATTLE_IS_UNAVAILABLE_RANK_FUND";
      
      public static const TEXT_SPECTATE_TEXT:String = "TEXT_SPECTATE_TEXT";
      
      public static const TEXT_PROFILE:String = "TEXT_PROFILE";
      
      public static const TEXT_DOM_WE_CAPTURED_POINT:String = "TEXT_DOM_WE_CAPTURED_POINT";
      
      public static const TEXT_DOM_ENEMIES_CAPTURED_POINT:String = "TEXT_DOM_ENEMIES_CAPTURED_POINT";
      
      public static const TEXT_DOM_WE_LOST_POINT:String = "TEXT_DOM_WE_LOST_POINT";
      
      public static const TEXT_DOM_ENEMIES_LOST_POINT:String = "TEXT_DOM_ENEMIES_LOST_POINT";
      
      public static const TEXT_DOM_BLUE_CAPTURED_POINT:String = "TEXT_DOM_BLUE_CAPTURED_POINT";
      
      public static const TEXT_DOM_RED_CAPTURED_POINT:String = "TEXT_DOM_RED_CAPTURED_POINT";
      
      public static const TEXT_DOM_BLUE_LOST_POINT:String = "TEXT_DOM_BLUE_LOST_POINT";
      
      public static const TEXT_DOM_RED_LOST_POINT:String = "TEXT_DOM_RED_LOST_POINT";
      
      public function §521423842397123423632234§()
      {
         super();
      }
   }
}

